In [1]:
!pip install tensorflow-gpu

     |████████████████████████████████| 320.4MB 48kB/s 


In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.__version__

'2.3.0'

# Constants



```
# This is formatted as code
```

#### Defining a constant

In [4]:
# Defining a constant in TensorFlow 2.0
tensor_20 = tf.constant([[23, 4], [32, 51]])

In [5]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [6]:
# Getting the shape of a tensor
tensor_20.shape

TensorShape([2, 2])

#### Getting the values of a constant

In [7]:
# Getting the values straight from a TensorFlow constant with numpy, and without the need of a session
tensor_20.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [8]:
# We are able to convert a numpy array back to a TensorFlow tensor as well
numpy_tensor = np.array([[23,  4], [32, 51]])

In [9]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [10]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 51]])>

### **Variables**

In [11]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

Getting the values of a variable

In [12]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

Changing a specific value in the variable

In [13]:
tf2_variable[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

Dot product between two tensors

In [15]:
tensor = tf.constant([[1, 2], [3, 4]])
np.dot(tensor, tensor_20)

array([[ 87, 106],
       [197, 216]], dtype=int32)